### ISSUE TITLE
GenericWork.generic_files access error

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra/sufia#1160]
Accessing work.generic_files is throwing an exception:

```
  1) CurationConcern::GenericWorkActor#create valid attributes with a present and a blank title should stamp each link with the access rights
     Failure/Error: expect(subject.create).to be true
     NoMethodError:
       undefined method `map' for #<ActiveFedora::LoadableFromJson::SolrBackedResource::FakeQuery:0x007fc4a7c50468>
     # ./sufia-models/app/jobs/copy_permissions_job.rb:16:in `run'
     # ./sufia-models/lib/sufia/models/resque.rb:32:in `perform'
     # ./sufia-models/lib/sufia/models/resque.rb:16:in `push'
     # ./sufia-models/app/actors/curation_concern/manages_permissions_actor.rb:24:in `copy_permissions'
     # ./sufia-models/app/actors/curation_concern/generic_work_actor.rb:9:in `create'
     # ./spec/actors/curation_concern/generic_work_actor_spec.rb:120:in `block (5 levels) in <top (required)>'
```

This is in the `real_integration` branch https://github.com/projecthydra/sufia/commits/real_integration

**Comment by mjgiarlo** [comment]
No longer relevant.
