### ISSUE TITLE
file_set parameter missing from upload

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1389]
This is preventing files from being uploaded

**Comment by awead** [comment]
Fixed in 8aa663b0071af2e8d9c96c7ea30a47569c775337

**Comment by jcoyne** [comment]
@awead closed?

**Comment by hectorcorrea** [comment]
@jcoyne @awead I don't think we can close this. I am getting the following error when uploading a file in Sufia from the "Share your Work" button (i.e. a file without a work)

```
Started POST "/concern/file_sets" for 127.0.0.1 at 2015-12-08 16:50:25 -0500
Processing by CurationConcerns::FileSetsController#create as JSON
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"zmXZpm80pk+ACadzspHI1RZ+iBfxtPM298uGC1L9jo7Iw9s1MEiMkS92ah3IF83vOuPKRz79vgvNs+5hye8NPw==", "total_upload_size"=>"157959", "relative_path"=>"", "upload_set_id"=>"t148fh47n", "parent_id"=>"", "file_coming_from"=>"local", "terms_of_service"=>"1", "file_set"=>{"files"=>[#<ActionDispatch::Http::UploadedFile:0x007fdc9deed280 @tempfile=#<Tempfile:/var/folders/pt/799s7l891j5dr807h3yt91yh0000gp/T/RackMultipart20151208-45196-1u2c6gv.pdf>, @original_filename="chapter_1.pdf", @content_type="application/pdf", @headers="Content-Disposition: form-data; name=\"file_set[files][]\"; filename=\"chapter_1.pdf\"\r\nContent-Type: application/pdf\r\n">]}}
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
   (0.1ms)  SELECT DISTINCT COUNT(DISTINCT "mailboxer_conversations"."id") FROM "mailboxer_conversations" INNER JOIN "mailboxer_notifications" ON "mailboxer_notifications"."conversation_id" = "mailboxer_conversations"."id" AND "mailboxer_notifications"."type" IN ('Mailboxer::Message') INNER JOIN "mailboxer_receipts" ON "mailboxer_receipts"."notification_id" = "mailboxer_notifications"."id" WHERE "mailboxer_notifications"."type" = 'Mailboxer::Message' AND "mailboxer_receipts"."mailbox_type" = ? AND "mailboxer_receipts"."trashed" = ? AND "mailboxer_receipts"."deleted" = ? AND "mailboxer_notifications"."type" = 'Mailboxer::Message' AND "mailboxer_receipts"."receiver_id" = ? AND "mailboxer_receipts"."receiver_type" = ? AND "mailboxer_receipts"."is_read" = ?  [["mailbox_type", "inbox"], ["trashed", "f"], ["deleted", "f"], ["receiver_id", 1], ["receiver_type", "User"], ["is_read", "f"]]
  Mailboxer::Conversation Load (0.3ms)  SELECT DISTINCT "mailboxer_conversations".* FROM "mailboxer_conversations" INNER JOIN "mailboxer_notifications" ON "mailboxer_notifications"."conversation_id" = "mailboxer_conversations"."id" AND "mailboxer_notifications"."type" IN ('Mailboxer::Message') INNER JOIN "mailboxer_receipts" ON "mailboxer_receipts"."notification_id" = "mailboxer_notifications"."id" WHERE "mailboxer_notifications"."type" = 'Mailboxer::Message' AND "mailboxer_receipts"."receiver_id" = ? AND "mailboxer_receipts"."receiver_type" = ? AND "mailboxer_receipts"."mailbox_type" = ? AND "mailboxer_receipts"."trashed" = ? AND "mailboxer_receipts"."deleted" = ?  ORDER BY mailboxer_conversations.updated_at DESC  [["receiver_id", 1], ["receiver_type", "User"], ["mailbox_type", "inbox"], ["trashed", "f"], ["deleted", "f"]]
Unpermitted parameter: files
Usergroups are ["public", "registered"]
Completed 500 Internal Server Error in 14ms (ActiveRecord: 0.5ms)

ArgumentError (wrong number of arguments (3 for 1..2)):
  /Users/hjc14/.gem/ruby/2.2.2/bundler/gems/curation_concerns-b16f25a935b5/curation_concerns-models/app/actors/curation_concerns/file_set_actor.rb:25:in `create_metadata'
  /Users/hjc14/dev/sufia/app/actors/sufia/file_set_actor.rb:7:in `create_metadata'
  /Users/hjc14/.gem/ruby/2.2.2/bundler/gems/curation_concerns-b16f25a935b5/app/controllers/concerns/curation_concerns/file_sets_controller_behavior.rb:189:in `process_file'
  /Users/hjc14/dev/sufia/app/controllers/concerns/sufia/files_controller_behavior.rb:68:in `process_file'
  /Users/hjc14/.gem/ruby/2.2.2/bundler/gems/curation_concerns-b16f25a935b5/app/controllers/concerns/curation_concerns/file_sets_controller_behavior.rb:44:in `create_from_upload'
  /Users/hjc14/.gem/ruby/2.2.2/bundler/gems/curation_concerns-b16f25a935b5/app/controllers/concerns/curation_concerns/file_sets_controller_behavior.rb:31:in `create'
  /Users/hjc14/dev/sufia/app/controllers/concerns/sufia/files_controller/browse_everything.rb:9:in `create'
  /Users/hjc14/dev/sufia/app/controllers/concerns/sufia/files_controller/local_ingest_behavior.rb:11:in `create'
  actionpack (4.2.5) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.5) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.5) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.5) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.5) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:76:in `call'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.5) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.5) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  active-fedora (9.7.0) lib/active_fedora/ldp_cache.rb:26:in `call'
  activerecord (4.2.5) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/hjc14/.rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/hjc14/.rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/hjc14/.rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'


  Rendered /Users/hjc14/.gem/ruby/2.2.2/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_source.erb (1.9ms)
  Rendered /Users/hjc14/.gem/ruby/2.2.2/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.5ms)
  Rendered /Users/hjc14/.gem/ruby/2.2.2/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (0.8ms)
  Rendered /Users/hjc14/.gem/ruby/2.2.2/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (34.9ms)
```

**Comment by awead** [comment]
That's due to projecthydra-labs/curation_concerns#544 once Sufia's fixed up because of that, it should work again.

**Comment by jcoyne** [comment]
This will be fixed by https://github.com/projecthydra/sufia/pull/1408
