### ISSUE TITLE
undefined method `permit' for nil:NilClass

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1434]
```
NoMethodError in UploadSetsController#update 
Application Trace | Framework Trace | Full Trace

hydra-editor (1.1.0) app/forms/hydra_editor/form.rb:67:in `sanitize_params'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-55686dce552c/app/forms/curation_concerns/forms/work_form.rb:53:in `sanitize_params'
hydra-editor (1.1.0) app/forms/hydra_editor/form.rb:59:in `model_attributes'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-55686dce552c/app/forms/curation_concerns/upload_set_form.rb:28:in `model_attributes'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-55686dce552c/app/controllers/concerns/curation_concerns/upload_sets_controller_behavior.rb:46:in `create_update_job'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-55686dce552c/app/controllers/concerns/curation_concerns/upload_sets_controller_behavior.rb:25:in `update'
```

**Comment by awead** [comment]
I've seen this before when hydra-editor calls `.permit` on an instance of `ActionController::Parameters` which should be the params that are getting passed to update, but evidently, that appears to be NilClass.

**Comment by jcoyne** [comment]
It also needs this update for the tests to pass: https://github.com/projecthydra/sufia/pull/1433
