### ISSUE TITLE
Work show page raises UrlGenerationError.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1442]
```
ActionController::UrlGenerationError in CurationConcerns::GenericWorks#show
actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:261:in `raise_generation_error'
actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:236:in `optimized_helper'
actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:222:in `call'
actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:347:in `block (2 levels) in define_url_helper'
/Users/justin/workspace/sufia/app/controllers/concerns/sufia/files_controller/upload_complete_behavior.rb:4:in `upload_complete_path'
/Users/justin/workspace/sufia/app/views/curation_concerns/file_sets/upload/_script_templates.html.erb:3:in `___sers_justin_workspace_sufia_app_views_curation_concerns_file_sets_upload__script_templates_html_erb___4303453964348103316_70268620524360'
actionview (4.2.5) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.5) lib/active_support/notifications.rb:166:in `instrument'
```

**Comment by jcoyne** [comment]
This is due to the  CurationConcerns::GenericWorks#show  not setting `@upload_set_id`
