### ISSUE TITLE
error on advanced search index page

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1450]
http://localhost:3000/advanced

```
current_ability has not been set on #<Sufia::SearchBuilder:0x007fb0196786f0>
hydra-access-controls (9.5.0) lib/hydra/access_controls_enforcement.rb:19:in `current_ability'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-3c56f74aa925/app/search_builders/curation_concerns/search_builder.rb:15:in `gated_discovery_filters'
hydra-access-controls (9.5.0) lib/hydra/access_controls_enforcement.rb:91:in `apply_gated_discovery'
hydra-access-controls (9.5.0) lib/hydra/access_controls_enforcement.rb:73:in `add_access_controls_to_solr_params'
blacklight (5.16.4) lib/blacklight/search_builder.rb:146:in `block (2 levels) in processed_parameters'
blacklight (5.16.4) lib/blacklight/search_builder.rb:141:in `each'
blacklight (5.16.4) lib/blacklight/search_builder.rb:141:in `block in processed_parameters'
blacklight (5.16.4) lib/blacklight/search_builder.rb:140:in `tap'
blacklight (5.16.4) lib/blacklight/search_builder.rb:140:in `processed_parameters'
blacklight (5.16.4) lib/blacklight/search_builder.rb:112:in `to_hash'
blacklight (5.16.4) lib/blacklight/solr/repository.rb:44:in `block in send_and_receive'
activesupport (4.2.5) lib/active_support/benchmarkable.rb:41:in `block in benchmark'
activesupport (4.2.5) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/justin/.rbenv/versions/2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
activesupport (4.2.5) lib/active_support/core_ext/benchmark.rb:12:in `ms'
activesupport (4.2.5) lib/active_support/benchmarkable.rb:41:in `benchmark'
blacklight (5.16.4) lib/blacklight/solr/repository.rb:42:in `send_and_receive'
blacklight (5.16.4) lib/blacklight/solr/repository.rb:28:in `search'
blacklight (5.16.4) app/controllers/concerns/blacklight/search_helper.rb:109:in `search_results'
blacklight_advanced_search (5.2.1) app/controllers/blacklight_advanced_search/advanced_controller.rb:16:in `get_advanced_search_facets'
blacklight_advanced_search (5.2.1) app/controllers/blacklight_advanced_search/advanced_controller.rb:7:in `index'
```

**Comment by mjgiarlo** [comment]
Resolving https://github.com/projecthydra-labs/curation_concerns/issues/555 should resolve this.

**Comment by grosscol** [comment]
The /advanced route should not be included since the advanced seearch engine of blacklight is not mounted.  Will be fixed in Blacklight6: https://github.com/projectblacklight/blacklight_advanced_search/commit/a582aa538f562826352a52a2790507b3088d59e9
