### ISSUE TITLE
Update to Rubocop 0.38

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1636]
### Descriptive summary

Sufia 7.0 should work with Rubcop 0.38.

### Expected behavior

It should work.

### Actual behavior

``` bash
/Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/lib/rubocop/config_loader.rb:40:in `require': cannot load such file -- /Users/awead/Projects/Github/projecthydra/sufia/rubocop-rspec (LoadError)
	from /Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/lib/rubocop/config_loader.rb:40:in `block in load_file'
	from /Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/lib/rubocop/config_loader.rb:39:in `each'
	from /Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/lib/rubocop/config_loader.rb:39:in `load_file'
	from /Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/lib/rubocop/config_loader.rb:99:in `configuration_from_file'
	from /Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/lib/rubocop/config_store.rb:41:in `for'
	from /Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/lib/rubocop/cli.rb:88:in `apply_default_formatter'
	from /Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/lib/rubocop/cli.rb:26:in `run'
	from /Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/bin/rubocop:14:in `block in <top (required)>'
	from /Users/awead/.rubies/ruby-2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
	from /Users/awead/.gem/ruby/2.2.3/gems/rubocop-0.38.0/bin/rubocop:13:in `<top (required)>'
	from /Users/awead/.gem/ruby/2.2.3/bin/rubocop:23:in `load'
	from /Users/awead/.gem/ruby/2.2.3/bin/rubocop:23:in `<main>'
```

### Steps to reproduce the behavior

1. Update rubocop
1. `bundle exec rubocop`

### Related work

See #1635 for related discussion.

**Comment by awead** [comment]
Recent changes to rubocop have changed the way it's requiring additional gems in `.rubocop.yml`. See:
https://github.com/bbatsov/rubocop/commit/5fdd79587090fd33a70e0b2be1138e391cd499e6
Now, when you run rubocop, the require statement in the yml file evaluates to:
`/Users/awead/Projects/Github/projecthydra/sufia/rubocop-rspec` where the base directory is the location of your sufia github repo.
