### ISSUE TITLE
Clicking on creator causes 500 internal server error

### ISSUE THREAD

**Issue by relaxing** [projecthydra/sufia#1972]
### Descriptive summary

Sufia HEAD commit 224101238189fbbf1ac5eb133c78f19d163eeae1

Solr parameters: {"facet.field"=>["resource_type_sim", "creator_sim", "tag_sim", "subject_sim", "language_sim", "based_near_sim", "publisher_sim", "file_format_sim"], "facet.query"=>[], "facet.pivot"=>[], "fq"=>["edit_access_group_ssim:public OR discover_access_group_ssim:public OR read_access_group_ssim:public OR edit_access_group_ssim:registered OR discover_access_group_ssim:registered OR read_access_group_ssim:registered OR edit_access_person_ssim:a@b.net OR discover_access_person_ssim:a@b.net OR read_access_person_ssim:a@b.net", "(_query_:\"{!field f=has_model_ssim}GenericWork\" OR _query_:\"{!field f=has_model_ssim}Collection\")", "edit_access_group_ssim:public OR discover_access_group_ssim:public OR read_access_group_ssim:public OR edit_access_group_ssim:registered OR discover_access_group_ssim:registered OR read_access_group_ssim:registered OR edit_access_person_ssim:a@b.net OR discover_access_person_ssim:a@b.net OR read_access_person_ssim:a@b.net"], "hl.fl"=>[], "qt"=>"search", "rows"=>10, "qf"=>"title_tesim name_tesim", "spellcheck.dictionary"=>"creator", "q"=>"{!qf=creator_tesim pf=creator_tesim}asdfsdfa", "spellcheck.q"=>"asdfsdfa", "facet"=>true, "f.resource_type_sim.facet.limit"=>6, "f.creator_sim.facet.limit"=>6, "f.tag_sim.facet.limit"=>6, "f.subject_sim.facet.limit"=>6, "f.language_sim.facet.limit"=>6, "f.based_near_sim.facet.limit"=>6, "f.publisher_sim.facet.limit"=>6, "f.file_format_sim.facet.limit"=>6, "sort"=>"score desc, system_create_dtsi desc"}
Completed 500 Internal Server Error in 34ms (ActiveRecord: 0.9ms)

Blacklight::Exceptions::InvalidRequest - RSolr::Error::Http - 500 Internal Server Error
Error: {'responseHeader'=>{'status'=>500,'QTime'=>11,'params'=>{'facet.field'=>['resource_type_sim','creator_sim','tag_sim','subject_sim','language_sim','based_near_sim','publisher_sim','file_format_sim'],'qt'=>'search','spellcheck.dictionary'=>'creator','user_query'=>'{!qf=creator_tesim pf=creator_tesim}asdfsdfa','f.language_sim.facet.limit'=>'6','f.file_format_sim.facet.limit'=>'6','f.based_near_sim.facet.limit'=>'6','f.publisher_sim.facet.limit'=>'6','fq'=>['edit_access_group_ssim:public OR discover_access_group_ssim:public OR read_access_group_ssim:public OR edit_access_group_ssim:registered OR discover_access_group_ssim:registered OR read_access_group_ssim:registered OR edit_access_person_ssim:a@b.net OR discover_access_person_ssim:a@b.net OR read_access_person_ssim:a@b.net','(_query_:"{!field f=has_model_ssim}GenericWork" OR _query_:"{!field f=has_model_ssim}Collection")','edit_access_group_ssim:public OR discover_access_group_ssim:public OR read_access_group_ssim:public OR edit_access_group_ssim:registered OR discover_access_group_ssim:registered OR read_access_group_ssim:registered OR edit_access_person_ssim:a@b.net OR discover_access_person_ssim:a@b.net OR read_access_person_ssim:a@b.net'],'f.resource_type_sim.facet.limit'=>'6','sort'=>'score desc, system_create_dtsi desc','rows'=>'10','f.creator_sim.facet.limit'=>'6','f.tag_sim.facet.limit'=>'6','q'=>'{!lucene}_query_:"{!dismax v=$user_query}" _query_:"{!join from=id to=file_set_ids_ssim}{!dismax v=$user_query}"','spellcheck.q'=>'asdfsdfa','defType'=>'dismax','qf'=>'title_tesim name_tesim','wt'=>'ruby','facet'=>'true','f.subject_sim.facet.limit'=>'6'}},'response'=>{'numFound'=>0,'start'=>0,'maxScore'=>0.0,'docs'=>[]},'facet_counts'=>{'facet_queries'=>{},'facet_fields'=>{'resource_type_sim'=>[],'creator_sim'=>[],'tag_sim'=>[],'subject_sim'=>[],'language_sim'=>[],'based_near_sim'=>[],'publisher_sim'=>[],'file_format_sim'=>[]},'facet_ranges'=>{},'facet_intervals'=>{},'facet_heatmaps'=>{}},'error'=>{'trace'=>'java.lang.NullPointerException
	at org.apache.solr.handler.component.SpellCheckComponent.process(SpellCheckComponent.java:153)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:287)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2033)
	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:652)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:460)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:229)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:184)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)

### Steps to reproduce the behavior

1. From the works show page
2. Click "creator" from the Metadata table

### Related work

Link to related tickets or prior related work here.

**Comment by mjgiarlo** [comment]
The link to creators looks like this in the works show page: `/catalog?q=Prof.+Bootsy+Collins&search_field=creator`

`/catalog?f%5Bcreator_sim%5D%5B%5D=Prof.+Bootsy+Collins`


```
Solr parameters: {"facet.field"=>["human_readable_type_sim", "resource_type_sim", "creator_sim", "tag_sim", "subject_sim", "language_sim", "based_near
_sim", "publisher_sim", "file_format_sim"], "facet.query"=>[], "facet.pivot"=>[], "fq"=>["edit_access_group_ssim:public OR discover_access_group_ssim:
public OR read_access_group_ssim:public OR edit_access_group_ssim:registered OR discover_access_group_ssim:registered OR read_access_group_ssim:regist
ered OR edit_access_person_ssim:mjgiarlo@stanford.edu OR discover_access_person_ssim:mjgiarlo@stanford.edu OR read_access_person_ssim:mjgiarlo@stanfor
d.edu"], "hl.fl"=>[], "qt"=>"search", "rows"=>10, "qf"=>"title_tesim name_tesim", "spellcheck.dictionary"=>"creator", "q"=>"{!qf=creator_tesim pf=crea
tor_tesim}Prof. Bootsy Collins", "spellcheck.q"=>"Prof. Bootsy Collins", "facet"=>true, "f.resource_type_sim.facet.limit"=>6, "f.creator_sim.facet.lim
it"=>6, "f.tag_sim.facet.limit"=>6, "f.subject_sim.facet.limit"=>6, "f.language_sim.facet.limit"=>6, "f.based_near_sim.facet.limit"=>6, "f.publisher_s
im.facet.limit"=>6, "f.file_format_sim.facet.limit"=>6, "sort"=>"score desc, system_create_dtsi desc"}
Solr parameters: {"facet.field"=>["human_readable_type_sim", "resource_type_sim", "creator_sim", "tag_sim", "subject_sim", "language_sim", "based_near
_sim", "publisher_sim", "file_format_sim"], "facet.query"=>[], "facet.pivot"=>[], "fq"=>["edit_access_group_ssim:public OR discover_access_group_ssim:
public OR read_access_group_ssim:public OR edit_access_group_ssim:registered OR discover_access_group_ssim:registered OR read_access_group_ssim:regist
ered OR edit_access_person_ssim:mjgiarlo@stanford.edu OR discover_access_person_ssim:mjgiarlo@stanford.edu OR read_access_person_ssim:mjgiarlo@stanfor
d.edu", "(_query_:\"{!field f=has_model_ssim}GenericWork\" OR _query_:\"{!field f=has_model_ssim}Collection\")", "edit_access_group_ssim:public OR dis
cover_access_group_ssim:public OR read_access_group_ssim:public OR edit_access_group_ssim:registered OR discover_access_group_ssim:registered OR read_
access_group_ssim:registered OR edit_access_person_ssim:mjgiarlo@stanford.edu OR discover_access_person_ssim:mjgiarlo@stanford.edu OR read_access_pers
on_ssim:mjgiarlo@stanford.edu"], "hl.fl"=>[], "qt"=>"search", "rows"=>10, "qf"=>"title_tesim name_tesim", "spellcheck.dictionary"=>"creator", "q"=>"{!
qf=creator_tesim pf=creator_tesim}Prof. Bootsy Collins", "spellcheck.q"=>"Prof. Bootsy Collins", "facet"=>true, "f.resource_type_sim.facet.limit"=>6, 
"f.creator_sim.facet.limit"=>6, "f.tag_sim.facet.limit"=>6, "f.subject_sim.facet.limit"=>6, "f.language_sim.facet.limit"=>6, "f.based_near_sim.facet.l
imit"=>6, "f.publisher_sim.facet.limit"=>6, "f.file_format_sim.facet.limit"=>6, "sort"=>"score desc, system_create_dtsi desc"}
Completed 500 Internal Server Error in 235ms (ActiveRecord: 23.1ms)

Blacklight::Exceptions::InvalidRequest - RSolr::Error::Http - 500 Internal Server Error
Error: {'responseHeader'=>{'status'=>500,'QTime'=>20,'params'=>{'facet.field'=>['human_readable_type_sim','resource_type_sim','creator_sim','tag_sim',
'subject_sim','language_sim','based_near_sim','publisher_sim','file_format_sim'],'qt'=>'search','spellcheck.dictionary'=>'creator','user_query'=>'{!qf
=creator_tesim pf=creator_tesim}Prof. Bootsy Collins','f.language_sim.facet.limit'=>'6','f.file_format_sim.facet.limit'=>'6','f.based_near_sim.facet.l
imit'=>'6','f.publisher_sim.facet.limit'=>'6','fq'=>['edit_access_group_ssim:public OR discover_access_group_ssim:public OR read_access_group_ssim:pub
lic OR edit_access_group_ssim:registered OR discover_access_group_ssim:registered OR read_access_group_ssim:registered OR edit_access_person_ssim:mjgi
arlo@stanford.edu OR discover_access_person_ssim:mjgiarlo@stanford.edu OR read_access_person_ssim:mjgiarlo@stanford.edu','(_query_:"{!field f=has_mode
l_ssim}GenericWork" OR _query_:"{!field f=has_model_ssim}Collection")','edit_access_group_ssim:public OR discover_access_group_ssim:public OR read_acc
ess_group_ssim:public OR edit_access_group_ssim:registered OR discover_access_group_ssim:registered OR read_access_group_ssim:registered OR edit_acces
s_person_ssim:mjgiarlo@stanford.edu OR discover_access_person_ssim:mjgiarlo@stanford.edu OR read_access_person_ssim:mjgiarlo@stanford.edu'],'f.resourc
e_type_sim.facet.limit'=>'6','sort'=>'score desc, system_create_dtsi desc','rows'=>'10','f.creator_sim.facet.limit'=>'6','f.tag_sim.facet.limit'=>'6',
'q'=>'{!lucene}_query_:"{!dismax v=$user_query}" _query_:"{!join from=id to=file_set_ids_ssim}{!dismax v=$user_query}"','spellcheck.q'=>'Prof. Bootsy 
Collins','defType'=>'dismax','qf'=>'title_tesim name_tesim','wt'=>'ruby','facet'=>'true','f.subject_sim.facet.limit'=>'6'}},'response'=>{'numFound'=>0
,'start'=>0,'maxScore'=>0.0,'docs'=>[]},'facet_counts'=>{'facet_queries'=>{},'facet_fields'=>{'human_readable_type_sim'=>[],'resource_type_sim'=>[],'c
reator_sim'=>[],'tag_sim'=>[],'subject_sim'=>[],'language_sim'=>[],'based_near_sim'=>[],'publisher_sim'=>[],'file_format_sim'=>[]},'facet_ranges'=>{},
'facet_intervals'=>{},'facet_heatmaps'=>{}},'error'=>{'trace'=>'java.lang.NullPointerException
        at org.apache.solr.handler.component.SpellCheckComponent.process(SpellCheckComponent.java:153)
        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:287)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:2033)
        at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:652)
        at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:460)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:229)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:184)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)

URI: http://127.0.0.1:8983/solr/hydra-development/select?wt=ruby&qt=search&facet.field=human_readable_type_sim&facet.field=resource_type_sim&facet.fie
ld=creator_sim&facet.field=tag_sim&facet.field=subject_sim&facet.field=language_sim&facet.field=based_near_sim&facet.field=publisher_sim&facet.field=f
ile_format_sim&&&fq=edit_access_group_ssim%3Apublic+OR+discover_access_group_ssim%3Apublic+OR+read_access_group_ssim%3Apublic+OR+edit_access_group_ssi
m%3Aregistered+OR+discover_access_group_ssim%3Aregistered+OR+read_access_group_ssim%3Aregistered+OR+edit_access_person_ssim%3Amjgiarlo%40stanford.edu+
OR+discover_access_person_ssim%3Amjgiarlo%40stanford.edu+OR+read_access_person_ssim%3Amjgiarlo%40stanford.edu&fq=%28_query_%3A%22%7B%21field+f%3Dhas_m
odel_ssim%7DGenericWork%22+OR+_query_%3A%22%7B%21field+f%3Dhas_model_ssim%7DCollection%22%29&fq=edit_access_group_ssim%3Apublic+OR+discover_access_gro
up_ssim%3Apublic+OR+read_access_group_ssim%3Apublic+OR+edit_access_group_ssim%3Aregistered+OR+discover_access_group_ssim%3Aregistered+OR+read_access_g
roup_ssim%3Aregistered+OR+edit_access_person_ssim%3Amjgiarlo%40stanford.edu+OR+discover_access_person_ssim%3Amjgiarlo%40stanford.edu+OR+read_access_pe
rson_ssim%3Amjgiarlo%40stanford.edu&&rows=10&qf=title_tesim+name_tesim&spellcheck.dictionary=creator&q=%7B%21lucene%7D_query_%3A%22%7B%21dismax+v%3D%2
4user_query%7D%22+_query_%3A%22%7B%21join+from%3Did+to%3Dfile_set_ids_ssim%7D%7B%21dismax+v%3D%24user_query%7D%22&spellcheck.q=Prof.+Bootsy+Collins&fa
cet=true&f.resource_type_sim.facet.limit=6&f.creator_sim.facet.limit=6&f.tag_sim.facet.limit=6&f.subject_sim.facet.limit=6&f.language_sim.facet.limit=
6&f.based_near_sim.facet.limit=6&f.publisher_sim.facet.limit=6&f.file_format_sim.facet.limit=6&sort=score+desc%2C+system_create_dtsi+desc&defType=dism
ax&user_query=%7B%21qf%3Dcreator_tesim+pf%3Dcreator_tesim%7DProf.+Bootsy+Collins

Backtrace: /home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/rsolr-1.1.1/lib/rsolr/client.rb:288:in `adapt_response'
/home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/rsolr-1.1.1/lib/rsolr/client.rb:189:in `execute'
/home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/rsolr-1.1.1/lib/rsolr/client.rb:175:in `send_and_receive'
/home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/blacklight-6.1.0/lib/blacklight/solr/repository.rb:39:in `block in send_and_receive'
/home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/activesupport-4.2.6/lib/active_support/benchmarkable.rb:41:in `block in benchmark'
/home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/activesupport-4.2.6/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home/mjg/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/activesupport-4.2.6/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/activesupport-4.2.6/lib/active_support/benchmarkable.rb:41:in `benchmark'
/home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/blacklight-6.1.0/lib/blacklight/solr/repository.rb:37:in `send_and_receive'
/home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/blacklight-6.1.0/lib/blacklight/solr/repository.rb:23:in `search':
  blacklight (6.1.0) lib/blacklight/solr/repository.rb:50:in `rescue in send_and_receive'
  blacklight (6.1.0) lib/blacklight/solr/repository.rb:37:in `send_and_receive'
  blacklight (6.1.0) lib/blacklight/solr/repository.rb:23:in `search'
  blacklight (6.1.0) app/controllers/concerns/blacklight/search_helper.rb:64:in `search_results'
  blacklight (6.1.0) app/controllers/concerns/blacklight/catalog.rb:25:in `index'
```

**Comment by mjgiarlo** [comment]
The link to creators looks like this in the works show page (and it breaks): `/catalog?q=Prof.+Bootsy+Collins&search_field=creator`

This link works, but it's obviously different: `/catalog?f%5Bcreator_sim%5D%5B%5D=Prof.+Bootsy+Collins`

Full traceback:

```
Solr parameters: {"facet.field"=>["human_readable_type_sim", "resource_type_sim", "creator_sim", "tag_sim", "subject_sim", "language_sim", "based_near
_sim", "publisher_sim", "file_format_sim"], "facet.query"=>[], "facet.pivot"=>[], "fq"=>["edit_access_group_ssim:public OR discover_access_group_ssim:
public OR read_access_group_ssim:public OR edit_access_group_ssim:registered OR discover_access_group_ssim:registered OR read_access_group_ssim:regist
ered OR edit_access_person_ssim:mjgiarlo@stanford.edu OR discover_access_person_ssim:mjgiarlo@stanford.edu OR read_access_person_ssim:mjgiarlo@stanfor
d.edu"], "hl.fl"=>[], "qt"=>"search", "rows"=>10, "qf"=>"title_tesim name_tesim", "spellcheck.dictionary"=>"creator", "q"=>"{!qf=creator_tesim pf=crea
tor_tesim}Prof. Bootsy Collins", "spellcheck.q"=>"Prof. Bootsy Collins", "facet"=>true, "f.resource_type_sim.facet.limit"=>6, "f.creator_sim.facet.lim
it"=>6, "f.tag_sim.facet.limit"=>6, "f.subject_sim.facet.limit"=>6, "f.language_sim.facet.limit"=>6, "f.based_near_sim.facet.limit"=>6, "f.publisher_s
im.facet.limit"=>6, "f.file_format_sim.facet.limit"=>6, "sort"=>"score desc, system_create_dtsi desc"}
Solr parameters: {"facet.field"=>["human_readable_type_sim", "resource_type_sim", "creator_sim", "tag_sim", "subject_sim", "language_sim", "based_near
_sim", "publisher_sim", "file_format_sim"], "facet.query"=>[], "facet.pivot"=>[], "fq"=>["edit_access_group_ssim:public OR discover_access_group_ssim:
public OR read_access_group_ssim:public OR edit_access_group_ssim:registered OR discover_access_group_ssim:registered OR read_access_group_ssim:regist
ered OR edit_access_person_ssim:mjgiarlo@stanford.edu OR discover_access_person_ssim:mjgiarlo@stanford.edu OR read_access_person_ssim:mjgiarlo@stanfor
d.edu", "(_query_:\"{!field f=has_model_ssim}GenericWork\" OR _query_:\"{!field f=has_model_ssim}Collection\")", "edit_access_group_ssim:public OR dis
cover_access_group_ssim:public OR read_access_group_ssim:public OR edit_access_group_ssim:registered OR discover_access_group_ssim:registered OR read_
access_group_ssim:registered OR edit_access_person_ssim:mjgiarlo@stanford.edu OR discover_access_person_ssim:mjgiarlo@stanford.edu OR read_access_pers
on_ssim:mjgiarlo@stanford.edu"], "hl.fl"=>[], "qt"=>"search", "rows"=>10, "qf"=>"title_tesim name_tesim", "spellcheck.dictionary"=>"creator", "q"=>"{!
qf=creator_tesim pf=creator_tesim}Prof. Bootsy Collins", "spellcheck.q"=>"Prof. Bootsy Collins", "facet"=>true, "f.resource_type_sim.facet.limit"=>6, 
"f.creator_sim.facet.limit"=>6, "f.tag_sim.facet.limit"=>6, "f.subject_sim.facet.limit"=>6, "f.language_sim.facet.limit"=>6, "f.based_near_sim.facet.l
imit"=>6, "f.publisher_sim.facet.limit"=>6, "f.file_format_sim.facet.limit"=>6, "sort"=>"score desc, system_create_dtsi desc"}
Completed 500 Internal Server Error in 235ms (ActiveRecord: 23.1ms)

Blacklight::Exceptions::InvalidRequest - RSolr::Error::Http - 500 Internal Server Error
Error: {'responseHeader'=>{'status'=>500,'QTime'=>20,'params'=>{'facet.field'=>['human_readable_type_sim','resource_type_sim','creator_sim','tag_sim',
'subject_sim','language_sim','based_near_sim','publisher_sim','file_format_sim'],'qt'=>'search','spellcheck.dictionary'=>'creator','user_query'=>'{!qf
=creator_tesim pf=creator_tesim}Prof. Bootsy Collins','f.language_sim.facet.limit'=>'6','f.file_format_sim.facet.limit'=>'6','f.based_near_sim.facet.l
imit'=>'6','f.publisher_sim.facet.limit'=>'6','fq'=>['edit_access_group_ssim:public OR discover_access_group_ssim:public OR read_access_group_ssim:pub
lic OR edit_access_group_ssim:registered OR discover_access_group_ssim:registered OR read_access_group_ssim:registered OR edit_access_person_ssim:mjgi
arlo@stanford.edu OR discover_access_person_ssim:mjgiarlo@stanford.edu OR read_access_person_ssim:mjgiarlo@stanford.edu','(_query_:"{!field f=has_mode
l_ssim}GenericWork" OR _query_:"{!field f=has_model_ssim}Collection")','edit_access_group_ssim:public OR discover_access_group_ssim:public OR read_acc
ess_group_ssim:public OR edit_access_group_ssim:registered OR discover_access_group_ssim:registered OR read_access_group_ssim:registered OR edit_acces
s_person_ssim:mjgiarlo@stanford.edu OR discover_access_person_ssim:mjgiarlo@stanford.edu OR read_access_person_ssim:mjgiarlo@stanford.edu'],'f.resourc
e_type_sim.facet.limit'=>'6','sort'=>'score desc, system_create_dtsi desc','rows'=>'10','f.creator_sim.facet.limit'=>'6','f.tag_sim.facet.limit'=>'6',
'q'=>'{!lucene}_query_:"{!dismax v=$user_query}" _query_:"{!join from=id to=file_set_ids_ssim}{!dismax v=$user_query}"','spellcheck.q'=>'Prof. Bootsy 
Collins','defType'=>'dismax','qf'=>'title_tesim name_tesim','wt'=>'ruby','facet'=>'true','f.subject_sim.facet.limit'=>'6'}},'response'=>{'numFound'=>0
,'start'=>0,'maxScore'=>0.0,'docs'=>[]},'facet_counts'=>{'facet_queries'=>{},'facet_fields'=>{'human_readable_type_sim'=>[],'resource_type_sim'=>[],'c
reator_sim'=>[],'tag_sim'=>[],'subject_sim'=>[],'language_sim'=>[],'based_near_sim'=>[],'publisher_sim'=>[],'file_format_sim'=>[]},'facet_ranges'=>{},
'facet_intervals'=>{},'facet_heatmaps'=>{}},'error'=>{'trace'=>'java.lang.NullPointerException
        at org.apache.solr.handler.component.SpellCheckComponent.process(SpellCheckComponent.java:153)
        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:287)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:2033)
        at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:652)
        at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:460)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:229)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:184)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)

URI: http://127.0.0.1:8983/solr/hydra-development/select?wt=ruby&qt=search&facet.field=human_readable_type_sim&facet.field=resource_type_sim&facet.fie
ld=creator_sim&facet.field=tag_sim&facet.field=subject_sim&facet.field=language_sim&facet.field=based_near_sim&facet.field=publisher_sim&facet.field=f
ile_format_sim&&&fq=edit_access_group_ssim%3Apublic+OR+discover_access_group_ssim%3Apublic+OR+read_access_group_ssim%3Apublic+OR+edit_access_group_ssi
m%3Aregistered+OR+discover_access_group_ssim%3Aregistered+OR+read_access_group_ssim%3Aregistered+OR+edit_access_person_ssim%3Amjgiarlo%40stanford.edu+
OR+discover_access_person_ssim%3Amjgiarlo%40stanford.edu+OR+read_access_person_ssim%3Amjgiarlo%40stanford.edu&fq=%28_query_%3A%22%7B%21field+f%3Dhas_m
odel_ssim%7DGenericWork%22+OR+_query_%3A%22%7B%21field+f%3Dhas_model_ssim%7DCollection%22%29&fq=edit_access_group_ssim%3Apublic+OR+discover_access_gro
up_ssim%3Apublic+OR+read_access_group_ssim%3Apublic+OR+edit_access_group_ssim%3Aregistered+OR+discover_access_group_ssim%3Aregistered+OR+read_access_g
roup_ssim%3Aregistered+OR+edit_access_person_ssim%3Amjgiarlo%40stanford.edu+OR+discover_access_person_ssim%3Amjgiarlo%40stanford.edu+OR+read_access_pe
rson_ssim%3Amjgiarlo%40stanford.edu&&rows=10&qf=title_tesim+name_tesim&spellcheck.dictionary=creator&q=%7B%21lucene%7D_query_%3A%22%7B%21dismax+v%3D%2
4user_query%7D%22+_query_%3A%22%7B%21join+from%3Did+to%3Dfile_set_ids_ssim%7D%7B%21dismax+v%3D%24user_query%7D%22&spellcheck.q=Prof.+Bootsy+Collins&fa
cet=true&f.resource_type_sim.facet.limit=6&f.creator_sim.facet.limit=6&f.tag_sim.facet.limit=6&f.subject_sim.facet.limit=6&f.language_sim.facet.limit=
6&f.based_near_sim.facet.limit=6&f.publisher_sim.facet.limit=6&f.file_format_sim.facet.limit=6&sort=score+desc%2C+system_create_dtsi+desc&defType=dism
ax&user_query=%7B%21qf%3Dcreator_tesim+pf%3Dcreator_tesim%7DProf.+Bootsy+Collins

Backtrace: /home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/rsolr-1.1.1/lib/rsolr/client.rb:288:in `adapt_response'
/home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/rsolr-1.1.1/lib/rsolr/client.rb:189:in `execute'
/home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/rsolr-1.1.1/lib/rsolr/client.rb:175:in `send_and_receive'
/home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/blacklight-6.1.0/lib/blacklight/solr/repository.rb:39:in `block in send_and_receive'
/home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/activesupport-4.2.6/lib/active_support/benchmarkable.rb:41:in `block in benchmark'
/home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/activesupport-4.2.6/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home/mjg/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/activesupport-4.2.6/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/activesupport-4.2.6/lib/active_support/benchmarkable.rb:41:in `benchmark'
/home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/blacklight-6.1.0/lib/blacklight/solr/repository.rb:37:in `send_and_receive'
/home/mjg/.rvm/gems/ruby-2.3.1@sufia/gems/blacklight-6.1.0/lib/blacklight/solr/repository.rb:23:in `search':
  blacklight (6.1.0) lib/blacklight/solr/repository.rb:50:in `rescue in send_and_receive'
  blacklight (6.1.0) lib/blacklight/solr/repository.rb:37:in `send_and_receive'
  blacklight (6.1.0) lib/blacklight/solr/repository.rb:23:in `search'
  blacklight (6.1.0) app/controllers/concerns/blacklight/search_helper.rb:64:in `search_results'
  blacklight (6.1.0) app/controllers/concerns/blacklight/catalog.rb:25:in `index'
```

**Comment by mjgiarlo** [comment]
Tagging Blacklight-y folks: @cbeer @jcoyne
