### ISSUE TITLE
Location authorities are broken

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2287]
```
Started GET "/authorities/generic_works/location?q=Saint" for ::1 at 2016-06-24 10:14:52 -0700
Processing by AuthoritiesController#query as JSON
Parameters: {"q"=>"Saint", "model"=>"generic_works", "term"=>"location"}
Completed 500 Internal Server Error in 308ms (ActiveRecord: 0.0ms)

Module::DelegationError - ActiveResource::Collection#each delegated to to_a.each, but to_a is nil: nil:
  activeresource (4.1.0) lib/active_resource/collection.rb:7:in `rescue in each'
  activeresource (4.1.0) lib/active_resource/collection.rb:7:in `each'
  activeresource (4.1.0) lib/active_resource/collection.rb:67:in `collect!'
  activeresource (4.1.0) lib/active_resource/base.rb:1043:in `instantiate_collection'
  /Users/jcoyne/workspace/sufia/app/models/geo_names_resource.rb:11:in `instantiate_collection'
  activeresource (4.1.0) lib/active_resource/base.rb:1012:in `find_every'
  activeresource (4.1.0) lib/active_resource/base.rb:919:in `find'
  /Users/jcoyne/workspace/sufia/app/models/geo_names_resource.rb:16:in `find_location'
  /Users/jcoyne/workspace/sufia/app/controllers/authorities_controller.rb:9:in `query'
```

**Comment by jcoyne** [comment]
I feel like we should get rid of the ActiveResource dependency and add a GeoNames driver to Questioning Authority.

**Comment by jcoyne** [comment]
Blocked by https://github.com/projecthydra-labs/questioning_authority/pull/90

**Comment by mjgiarlo** [comment]
Merged
