### ISSUE TITLE
Cannot run sufia:install generator in Sufia 7.0.0.beta4

### ISSUE THREAD

**Issue by electrickite** [projecthydra/sufia#2323]
### Descriptive summary

Cannot run sufia:install generator in Sufia 7.0.0.beta4 or latest Sufia 7 HEAD. 

### Expected behavior

Run `rails generate sufia:install -f`
Generator runs successfully with no errors.

### Actual behavior

Generator throws several errors while running, from the noid rake task.

```rake aborted!
NoMethodError: undefined method `gem_dir' for nil:NilClass
/Users/hinshaw.25/.gem/ruby/2.3.1/gems/sufia-7.0.0.beta4/tasks/noid.rake:3:in `<top (required)>'
/Users/hinshaw.25/.gem/ruby/2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/Users/hinshaw.25/.gem/ruby/2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
/Users/hinshaw.25/.gem/ruby/2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/hinshaw.25/.gem/ruby/2.3.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/Users/hinshaw.25/.gem/ruby/2.3.1/gems/sufia-7.0.0.beta4/lib/sufia/engine.rb:24:in `block in <class:Engine>'
/Users/hinshaw.25/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/railtie.rb:237:in `instance_exec'
/Users/hinshaw.25/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/railtie.rb:237:in `block in run_tasks_blocks'
/Users/hinshaw.25/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/railtie.rb:245:in `each'
/Users/hinshaw.25/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/railtie.rb:245:in `each_registered_block'
/Users/hinshaw.25/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/railtie.rb:237:in `run_tasks_blocks'
/Users/hinshaw.25/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/engine.rb:657:in `run_tasks_blocks'
/Users/hinshaw.25/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/application.rb:451:in `block in run_tasks_blocks'
/Users/hinshaw.25/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/engine/railties.rb:13:in `each'
/Users/hinshaw.25/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/engine/railties.rb:13:in `each'
/Users/hinshaw.25/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/application.rb:451:in `run_tasks_blocks'
/Users/hinshaw.25/.gem/ruby/2.3.1/gems/railties-4.2.6/lib/rails/engine.rb:453:in `load_tasks'
/Users/hinshaw.25/projects/dcs/Rakefile:6:in `<top (required)>'
/Users/hinshaw.25/.gem/ruby/2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)```

### Steps to reproduce the behavior

1. `rails new sufia7`
2. `cd sufia7`
3. `echo "gem 'sufia', '7.0.0.beta4'" >> Gemfile`
4. `bundle install`
5. `rails generate sufia:install -f`

### Related work

Because the `active_fedora-noid` gem is specified with a pre-release version (2.0.0.beta1), this may be related to a Rubygems bug: https://github.com/rubygems/rubygems/issues/988

**Comment by kerchner** [comment]
Similar error here with similar steps:
```
/opt/scholarspace/scholarspace/config/initializers/curation_concerns.rb:1:in `<top (required)>': undefined method `configure' for CurationConcerns:Module (NoMethodError)
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/engine.rb:652:in `block in load_config_initializer'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/engine.rb:651:in `load_config_initializer'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/engine.rb:615:in `each'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/engine.rb:615:in `block in <class:Engine>'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
	from /opt/scholarspace/scholarspace/config/environment.rb:5:in `<top (required)>'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/spring-1.7.2/lib/spring/application.rb:92:in `preload'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/spring-1.7.2/lib/spring/application.rb:143:in `serve'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
	from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by electrickite** [comment]
A workaround is to specify that `active_fedora-noid` is pulled from git in your `Gemfile`. Right now, the version is 2.0.0.beta1, which is commit 8107a47

`gem 'active_fedora-noid', :git => 'https://github.com/projecthydra-labs/active_fedora-noid.git', ref: '8107a47121919ab250784b22e6ee7b066fa711db'`

**Comment by awead** [comment]
This will be fixed in https://github.com/projecthydra/sufia/pull/2318

**Comment by mjgiarlo** [comment]
I wonder if CC or Sufia should pin AF::Noid to < 2 in the meantime.

**Comment by rotated8** [comment]
Bundler also allows you to specify tags, and github repos without the full url:

`gem 'active_fedora-noid', github: 'projecthydra-labs/active_fedora-noid', tag: 'v2.0.0.beta1'`

**Comment by awead** [comment]
@electrickite can we close this?

**Comment by electrickite** [comment]
Just tried again with a fresh Rails app and Sufia 7.0.0.rc1 and I did not encounter the same errors. Closing.
