### ISSUE TITLE
Installing migrations creates migrations that aren't usable

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2678]
Running: 
```
$ rails sufia:install:migrations
```

installs:
```
	db/migrate/20160913144317_change_trophy_generic_file_id_to_work_id.sufia.rb
	db/migrate/20160913144318_change_proxy_deposit_generic_file_id_to_work_id.sufia.rb
	db/migrate/20160913144319_change_proxy_deposit_request_generic_file_id_to_work_id.sufia.rb
	db/migrate/20160913144320_change_featured_work_generic_file_id_to_work_id.sufia.rb
	db/migrate/20160913144321_add_arkivo_to_users.sufia.rb
```

then when you type `rake db:migrate`
You get errors like:

```

PG::UndefinedColumn: ERROR:  column "generic_file_id" does not exist
: ALTER TABLE "trophies" RENAME COLUMN "generic_file_id" TO "work_id"
/Users/jcoyne/workspace/lerna/db/migrate/20160913144317_change_trophy_generic_file_id_to_work_id.sufia.rb:4:in `change'
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "generic_file_id" does not exist
: ALTER TABLE "trophies" RENAME COLUMN "generic_file_id" TO "work_id"
/Users/jcoyne/workspace/lerna/db/migrate/20160913144317_change_trophy_generic_file_id_to_work_id.sufia.rb:4:in `change'
PG::UndefinedColumn: ERROR:  column "generic_file_id" does not exist
/Users/jcoyne/workspace/lerna/db/migrate/20160913144317_change_trophy_generic_file_id_to_work_id.sufia.rb:4:in `change'
Tasks: TOP => db:migrate
```

**Comment by jcoyne** [comment]
Caused by renaming of migrations that occurred in 7f94d38bc366c7760aaa5eead3d65a2826f01518
