### ISSUE TITLE
Batch Create work throws an exception

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2755]
### Descriptive summary

When I batch create works and I hit save I get an error

### Expected behavior

It should not blow up and should create mutiple works

### Actual behavior

```
ActiveJob::SerializationError - Unsupported argument type: ActionController::Parameters:
  activejob (5.0.0.1) lib/active_job/arguments.rb:83:in `serialize_argument'
  activejob (5.0.0.1) lib/active_job/arguments.rb:44:in `block in serialize'
  activejob (5.0.0.1) lib/active_job/arguments.rb:44:in `serialize'
  activejob (5.0.0.1) lib/active_job/core.rb:123:in `serialize_arguments'
  activejob (5.0.0.1) lib/active_job/core.rb:81:in `serialize'
  activejob (5.0.0.1) lib/active_job/queue_adapters/async_adapter.rb:64:in `initialize'
  activejob (5.0.0.1) lib/active_job/queue_adapters/async_adapter.rb:38:in `enqueue'
  activejob (5.0.0.1) lib/active_job/enqueuing.rb:76:in `block in enqueue'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:126:in `call'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:455:in `call'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
  activejob (5.0.0.1) lib/active_job/logging.rb:15:in `block (3 levels) in <module:Logging>'
  activejob (5.0.0.1) lib/active_job/logging.rb:44:in `block in tag_logger'
  activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
  activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'
  activejob (5.0.0.1) lib/active_job/logging.rb:44:in `tag_logger'
  activejob (5.0.0.1) lib/active_job/logging.rb:14:in `block (2 levels) in <module:Logging>'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:391:in `block in make_lambda'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:285:in `block in halting'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:447:in `block in around'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:455:in `call'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_enqueue_callbacks'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
  activejob (5.0.0.1) lib/active_job/enqueuing.rb:72:in `enqueue'
  activejob (5.0.0.1) lib/active_job/enqueuing.rb:18:in `perform_later'
  /Users/cam156/sufia/app/controllers/concerns/sufia/batch_uploads_controller_behavior.rb:43:in `create_update_job'
  /Users/cam156/sufia/app/controllers/concerns/sufia/batch_uploads_controller_behavior.rb:13:in `create'
  actionpack (5.0.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  actionpack (5.0.0.1) lib/abstract_controller/base.rb:188:in `process_action'
  actionpack (5.0.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
  actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:126:in `call'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:455:in `call'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
  actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (5.0.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
  actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (5.0.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (5.0.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
  activerecord (5.0.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (5.0.0.1) lib/abstract_controller/base.rb:126:in `process'
  actionview (5.0.0.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (5.0.0.1) lib/action_controller/metal.rb:190:in `dispatch'
  actionpack (5.0.0.1) lib/action_controller/metal.rb:262:in `dispatch'
  actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
  actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
  actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
  actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
  railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
  railties (5.0.0.1) lib/rails/railtie.rb:193:in `method_missing'
  actionpack (5.0.0.1) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
  actionpack (5.0.0.1) lib/action_dispatch/routing/mapper.rb:46:in `serve'
  actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
  actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
  actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (2.0.1) lib/rack/etag.rb:25:in `call'
  rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'
  rack (2.0.1) lib/rack/head.rb:12:in `call'
  rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
  rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
  active-fedora (11.0.1) lib/active_fedora/ldp_cache.rb:26:in `call'
   () Users/cam156/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/flipflop-0eecddade989/lib/flipflop/feature_cache.rb:12:in `call'
  activerecord (5.0.0.1) lib/active_record/migration.rb:552:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'
  railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'
  activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
  activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'
  railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'
  sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
  rack (2.0.1) lib/rack/method_override.rb:22:in `call'
  rack (2.0.1) lib/rack/runtime.rb:22:in `call'
  activesupport (5.0.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.0.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
  rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
  railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
  puma (3.6.0) lib/puma/configuration.rb:225:in `call'
  puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
  puma (3.6.0) lib/puma/server.rb:415:in `process_client'
  puma (3.6.0) lib/puma/server.rb:275:in `block in run'
  puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

### Steps to reproduce the behavior

1. Click on "Batch Create Works"
1. Select Multiple Files
1. Fill in metadata
1. Click save

**Comment by awead** [comment]
Looks like the job is getting send the whole parameter hash instead of a string or other parameter. Active::Job is picky about what it takes, for example, it won't take symbols:

https://github.com/rails/rails/blob/master/activejob/lib/active_job/arguments.rb#L38

**Comment by awead** [comment]
I wonder why this started happening. AJ will accept a hash and hash-like parameters:

https://github.com/rails/rails/blob/master/activejob/lib/active_job/arguments.rb#L77

But I guess not `ActionController::Parameters`. I wonder if we could file a PR to allow them, or make attributes_for_actors more hash-y? 🍳

**Comment by hackmastera** [comment]
Following. Any idea when this started? It seems okay in 7.1

**Comment by jcoyne** [comment]
I'll bet you this is a Rails 4/5 issue.

**Comment by jcoyne** [comment]
Probably just need to change https://github.com/projecthydra/sufia/blob/master/app/controllers/concerns/sufia/batch_uploads_controller_behavior.rb#L47 to be `attributes_for_actor.respond_to?(:to_unsafe_h) ? attributes_for_actor.to_unsafe_h : attributes_for_actor`
