### ISSUE TITLE
Error running sufia:work generator

### ISSUE THREAD

**Issue by phebal** [projecthydra/sufia#2771]
### Descriptive summary

Using Sufia 7.2.0, following the README on how to generate Sufia 7 app. Running `rails generate sufia:work Work` breaks with the the following error:

```
      insert  config/initializers/sufia.rb
/home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `binread': No such file or directory @ rb_sysopen - /home/phb010/sufia7/config/initializers/sufia.rb (Errno::ENOENT)
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `replace!'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:59:in `invoke!'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:30:in `insert_into_file'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/sufia-7.2.0/lib/generators/sufia/work_generator.rb:19:in `register_work'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/generators.rb:180:in `invoke'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:138:in `require_command!'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:145:in `generate_or_destroy'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:60:in `generate'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /home/phb010/sufia7/bin/rails:9:in `<top (required)>'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/phb010/sufia7/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /home/phb010/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/phb010/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

It can be convinced to work by running:
`touch config/initializers/sufia.rb`

### Expected behavior

It finishes generating Sufia files.

### Actual behavior

Breaks in the middle of generating Sufia files.

### Steps to reproduce the behavior

1. `rm -f config/initializers/sufia.rb`
2. `rails generate sufia:work Work`

**Comment by jcoyne** [comment]
Did you run `rails generate sufia:install` prior to generating the work?

**Comment by phebal** [comment]
Oh man, must have missed a step. Sorry about that, and thanks for your response.

**Comment by mjgiarlo** [comment]
No worries, @phebal. And do check out the 7.2.0 release notes if you haven't yet -- there is one step you'll need to take before the install generator will work (related to the `flipflop` gem).
