### ISSUE TITLE
Error: Hydra::AccessControls::Permission::GeneratedResourceSchema is immutable

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#2821]
### Descriptive summary

Given I have a work with existing permisisons
If those permissions are removed and then re-added again via the UI
Then I get an error
### Expected behavior

I think the UI needs to identify "newly" added permissions inserted into the table, that are actually the same as ones that have just been removed from the table, but are still present on the object.
### Actual behavior

We get an error. See the stack trace below.
### Steps to reproduce the behavior
1. Build the internal app
2. Sign with two users: user1 and user2
3. As user2, create a new work
4. Edit its permissions so that user1 has view/download permissions
5. Save and re-edit the work
6. From the Share tab, remove user1's permissions by clicking the "x"
7. Add back the exact same permissions via the UI: user1 has view/download permissions
8. Save
### Related work

I think this is what's behind https://github.com/projecthydra/sufia/issues/2737 but the ticket isn't as well-articulated.
### Stack trace

```
Completed 500 Internal Server Error in 1022ms (ActiveRecord: 0.4ms)

TypeError - #<Hydra::AccessControls::Permission::GeneratedResourceSchema:0x007fb69a4c9930> is immutable:
  rdf (2.1.0) lib/rdf/mixin/mutable.rb:155:in `delete'
  active-triples (0.11.0) lib/active_triples/relation.rb:210:in `clear'
  active-triples (0.11.0) lib/active_triples/relation.rb:390:in `set'
  active-triples (0.11.0) lib/active_triples/rdf_source.rb:439:in `set_value'
  active-fedora (11.0.1) lib/active_fedora/fedora_attributes.rb:33:in `set_value'
  active-fedora (11.0.1) lib/active_fedora/attribute_methods/dirty.rb:11:in `set_value'
  active-fedora (11.0.1) lib/active_fedora/attributes/property_builder.rb:21:in `agent='
  hydra-access-controls (10.3.0) app/models/hydra/access_controls/permission.rb:59:in `build_agent'
  hydra-access-controls (10.3.0) app/models/hydra/access_controls/permission.rb:33:in `assign_attributes'
  active-fedora (11.0.1) lib/active_fedora/persistence.rb:38:in `update'
  hydra-access-controls (10.3.0) app/models/hydra/access_control.rb:29:in `block in permissions_attributes='
  hydra-access-controls (10.3.0) app/models/hydra/access_control.rb:23:in `permissions_attributes='
  hydra-access-controls (10.3.0) app/models/concerns/hydra/access_controls/permissions.rb:21:in `permissions_attributes_without_uniqueness='
  hydra-access-controls (10.3.0) app/models/concerns/hydra/access_controls/permissions.rb:64:in `permissions_attributes='
  active-fedora (11.0.1) lib/active_fedora/attribute_assignment.rb:51:in `_assign_attribute'
  active-fedora (11.0.1) lib/active_fedora/attribute_assignment.rb:45:in `block in _assign_attributes'
  active-fedora (11.0.1) lib/active_fedora/attribute_assignment.rb:44:in `_assign_attributes'
  active-fedora (11.0.1) lib/active_fedora/attribute_assignment.rb:38:in `assign_attributes'
  active-fedora (11.0.1) lib/active_fedora/attribute_assignment.rb:9:in `attributes='
  active-fedora (11.0.1) lib/active_fedora/attributes/serializers.rb:24:in `attributes='
  curation_concerns (1.6.3) app/actors/curation_concerns/actors/base_actor.rb:56:in `apply_save_data_to_curation_concern'
  curation_concerns (1.6.3) app/actors/curation_concerns/actors/base_actor.rb:20:in `update'
  curation_concerns (1.6.3) app/actors/curation_concerns/actors/actor_stack.rb:27:in `update'
  curation_concerns (1.6.3) app/actors/curation_concerns/actors/interpret_visibility_actor.rb:79:in `update'
  curation_concerns (1.6.3) app/actors/curation_concerns/actors/actor_stack.rb:27:in `update'
  curation_concerns (1.6.3) app/actors/curation_concerns/actors/apply_order_actor.rb:7:in `update'
  curation_concerns (1.6.3) app/actors/curation_concerns/actors/actor_stack.rb:27:in `update'
  curation_concerns (1.6.3) app/actors/curation_concerns/actors/attach_files_actor.rb:12:in `update'
  curation_concerns (1.6.3) app/actors/curation_concerns/actors/actor_stack.rb:27:in `update'
  curation_concerns (1.6.3) app/actors/curation_concerns/actors/abstract_actor.rb:27:in `update'
  curation_concerns (1.6.3) app/actors/curation_concerns/actors/actor_stack.rb:27:in `update'
  curation_concerns (1.6.3) app/actors/curation_concerns/actors/add_to_work_actor.rb:11:in `update'
  curation_concerns (1.6.3) app/actors/curation_concerns/actors/actor_stack.rb:27:in `update'
  curation_concerns (1.6.3) app/actors/curation_concerns/actors/add_to_collection_actor.rb:11:in `update'
  curation_concerns (1.6.3) app/actors/curation_concerns/actors/actor_stack.rb:27:in `update'
  /Users/awead/Projects/Github/projecthydra/sufia/app/actors/sufia/create_with_files_actor.rb:11:in `update'
  curation_concerns (1.6.3) app/actors/curation_concerns/actors/actor_stack.rb:27:in `update'
  /Users/awead/Projects/Github/projecthydra/sufia/app/actors/sufia/create_with_remote_files_actor.rb:11:in `update'
  curation_concerns (1.6.3) app/actors/curation_concerns/actors/actor_stack.rb:27:in `update'
  curation_concerns (1.6.3) app/controllers/concerns/curation_concerns/curation_concern_controller.rb:81:in `update'
  actionpack (4.2.7) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.7) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.7) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.7) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.7) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.7) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.7) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.7) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.7) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.7) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.7) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.7) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.7) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.7) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.7) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.7) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.7) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.7) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.7) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.7) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.7) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.7) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.7) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.7) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.7) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.7) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.7) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.7) lib/action_dispatch/routing/route_set.rb:817:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.7) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  active-fedora (11.0.1) lib/active_fedora/ldp_cache.rb:26:in `call'
   () Users/awead/.gem/ruby/2.3.1/bundler/gems/flipflop-0eecddade989/lib/flipflop/feature_cache.rb:12:in `call'
  activerecord (4.2.7) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.7) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.7) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.7) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.7) lib/rails/engine.rb:518:in `call'
  railties (4.2.7) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/awead/.rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /Users/awead/.rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /Users/awead/.rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by awead** [comment]
Here's what I think is happening. In hydra-access-controls, `app/models/concerns/hydra/access_controls/permissions.rb:64` we're trying to set `permissions_attributes_without_uniqueness` to something like:

``` ruby
[
  {
    "access"=>"read", 
    "id"=>"2e425a0d-213d-4e06-9568-4ca8faefb9ac/a6/98/d5/b3/a698d5b3-d1d4-4ab8-8a26-ee32a77968ba",
    "_destroy"=>"true"
  }, 
  {
    "type"=>"group",
    "name"=>"umg/up.its.scholarsphere-support.admin",
    "access"=>"read",
    "id"=>"2e425a0d-213d-4e06-9568-4ca8faefb9ac/a6/98/d5/b3/a698d5b3-d1d4-4ab8-8a26-ee32a77968ba"
  }
]
```

So, simultaneously adding and destroying at the same time.

**Comment by mjgiarlo** [comment]
@awead are you still working on this?

**Comment by awead** [comment]
@mjgiarlo I think it's fixed now with the above commit to hydra-head.
