### ISSUE TITLE
Upload to Admin Set fails when there is no approver

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2990]
### Descriptive summary

In Sufia 7 When I upload a work into an Admin Set with no approver, then I get an error after I hit save.

### Expected behavior

The creator of the admin set should get approval rights.  This was implemented in hyrax: https://github.com/projecthydra-labs/hyrax/commit/c225f6a93049596724e8733634f0dae378256fe5

If this is set then there would not be an admin set that did not have an approver, unless someone went in and removed the approver, so we should also do a check to be certain that the approver exists before sending the message.

### Actual behavior

```
NoMethodError - undefined method `workflow' for nil:NilClass:
  curation_concerns (1.7.1) app/views/curation_concerns/base/unavailable.html.erb:2:in `___sers_cam_____rbenv_versions_______lib_ruby_gems_______gems_curation_concerns_______app_views_curation_concerns_base_unavailable_html_erb__1824529489049568194_70096225026800'
  actionview (5.0.1) lib/action_view/template.rb:159:in `block in render'
  activesupport (5.0.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (5.0.1) lib/action_view/template.rb:354:in `instrument'
  actionview (5.0.1) lib/action_view/template.rb:157:in `render'
  actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
  activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (5.0.1) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
  actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (5.0.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (5.0.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (5.0.1) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (5.0.1) lib/action_view/rendering.rb:103:in `_render_template'
  actionpack (5.0.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (5.0.1) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (5.0.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
  actionpack (5.0.1) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
  actionpack (5.0.1) lib/abstract_controller/rendering.rb:26:in `render'
  actionpack (5.0.1) lib/action_controller/metal/rendering.rb:36:in `render'
  actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (5.0.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/cam156/.rbenv/versions/2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
  activesupport (5.0.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
  curation_concerns (1.7.1) app/controllers/concerns/curation_concerns/curation_concern_controller.rb:221:in `block (2 levels) in render_unavailable'
  actionpack (5.0.1) lib/action_controller/metal/mime_responds.rb:201:in `respond_to'
  curation_concerns (1.7.1) app/controllers/concerns/curation_concerns/curation_concern_controller.rb:218:in `render_unavailable'
  activesupport (5.0.1) lib/active_support/rescuable.rb:101:in `block in handler_for_rescue'
  activesupport (5.0.1) lib/active_support/rescuable.rb:89:in `rescue_with_handler'
  activesupport (5.0.1) lib/active_support/rescuable.rb:158:in `rescue_with_handler'
  actionpack (5.0.1) lib/action_controller/metal/rescue.rb:23:in `rescue in process_action'
  actionpack (5.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
  actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (5.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
  activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (5.0.1) lib/abstract_controller/base.rb:126:in `process'
  actionview (5.0.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (5.0.1) lib/action_controller/metal.rb:190:in `dispatch'
  actionpack (5.0.1) lib/action_controller/metal.rb:262:in `dispatch'
  actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
  actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
  actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
  actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (2.0.1) lib/rack/etag.rb:25:in `call'
  rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
  rack (2.0.1) lib/rack/head.rb:12:in `call'
  rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
  rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
  actionpack (5.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
  active-fedora (11.0.1) lib/active_fedora/ldp_cache.rb:26:in `call'
   () Users/cam156/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/flipflop-0eecddade989/lib/flipflop/feature_cache.rb:12:in `call'
  activerecord (5.0.1) lib/active_record/migration.rb:553:in `call'
  actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
  activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
  activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
  activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
  actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
  actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
  actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
  railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
  activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
  activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
  railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
  sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
  actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
  rack (2.0.1) lib/rack/method_override.rb:22:in `call'
  rack (2.0.1) lib/rack/runtime.rb:22:in `call'
  activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
  rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
  railties (5.0.1) lib/rails/engine.rb:522:in `call'
  puma (3.6.2) lib/puma/configuration.rb:225:in `call'
  puma (3.6.2) lib/puma/server.rb:578:in `handle_request'
  puma (3.6.2) lib/puma/server.rb:415:in `process_client'
  puma (3.6.2) lib/puma/server.rb:275:in `block in run'
  puma (3.6.2) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

### Steps to reproduce the behavior

1. Create a new Admin Set
1. Do NOT give anyone Aproval rights
1. Upload a work to the new Admin Set
1. You should see the error once you hit save

### Related work

Link to related tickets or prior related work here.

**Comment by jcoyne** [comment]
Given the stack trace you are displaying here, it look like the error is due to the `@presenter` not being set.

**Comment by mjgiarlo** [comment]
Thanks for reporting this, @cam156!

**Comment by cam156** [comment]
@mjgiarlo and others I can remove the failure by setting the presenter in Curation Concerns.  Do we still want to set a default approver?  I think I was not seeing the error becuase I was an approver so WorkFlow exception was not being thrown.

**Comment by mjgiarlo** [comment]
@cam156 If we do set a default approver, I'm guessing that should be a separate enhancement PR. Thoughts on this, @vantuyls @scholarworks?

**Comment by jcoyne** [comment]
I'm guessing the presence of an approver doesn't have anything to do with this problem. Because @cam156 was the approver, then she wasn't seeing the unavailable template.
