### ISSUE TITLE
Handle error when there is no minter_statefile

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#368]
```

Errno::ENOENT in GenericFilesController#new
No such file or directory - /tmp/minter-state

Rails.root: C:/rubystack1.9/ruby/lib/ruby/gems/1.9.1/gems/sufia_app
Application Trace | Framework Trace | Full Trace

sufia-models (3.7.2) lib/sufia/models/id_service.rb:32:in `initialize'
sufia-models (3.7.2) lib/sufia/models/id_service.rb:32:in `open'
sufia-models (3.7.2) lib/sufia/models/id_service.rb:32:in `next_id'
sufia-models (3.7.2) lib/sufia/models/id_service.rb:22:in `block in mint'
<internal:prelude>:10:in `synchronize'
sufia-models (3.7.2) lib/sufia/models/id_service.rb:20:in `mint'
sufia (3.7.2) lib/sufia/files_controller_behavior.rb:46:in `new'
```

**Comment by mjgiarlo** [comment]
Never confirmed to be a problem outside of the Windows environment, which we have never said we support.  Closing.
