### ISSUE TITLE
Error on metadata save with 6.0.0.rc1

### ISSUE THREAD

**Issue by acozine** [projecthydra/sufia#837]
On demo.curationexperts.com, using Fedora 4, when I upload a new object, the object is saved and I can enter metadata. When I try to save the metadata page, the save fails.
 
Stacktrace:
```
F, [2015-01-08T16:51:19.007206 #5482] FATAL -- : 
ActionView::Template::Error (ActiveFedora::ObjectNotFoundError):
     5:     <label for="batch_document_<%= document.id %>" class="sr-only"><%=t("sufia.dashboard.my.sr.batch_checkbox")%></label>
     6:     <%= batch_edit_select(document) %>&nbsp;
     7:     <%# This block is for adding/removing the magic wand while batch updates are processing %>
     8:     <% if gf.processing? %>
     9:         <i class="glyphicon glyphicon-time <%= 'ss-'+gf.batch.noid %>"/>
    10:     <% elsif gf.depositor != @user.user_key %>
    11:         <i class="glyphicon glyphicon-share-alt"/>
  active-fedora (9.0.0.rc2) lib/active_fedora/relation/finder_methods.rb:192:in `load_from_fedora'
  active-fedora (9.0.0.rc2) lib/active_fedora/relation/finder_methods.rb:128:in `block (2 levels) in find_each'
  active-fedora (9.0.0.rc2) lib/active_fedora/relation/finder_methods.rb:126:in `each'
  active-fedora (9.0.0.rc2) lib/active_fedora/relation/finder_methods.rb:126:in `block in find_each'
  active-fedora (9.0.0.rc2) lib/active_fedora/relation/finder_methods.rb:166:in `find_in_batches'
  active-fedora (9.0.0.rc2) lib/active_fedora/relation/finder_methods.rb:125:in `find_each'
  active-fedora (9.0.0.rc2) lib/active_fedora/relation.rb:60:in `each'
  active-fedora (9.0.0.rc2) lib/active_fedora/relation.rb:60:in `to_a'
  active-fedora (9.0.0.rc2) lib/active_fedora/relation.rb:60:in `to_a'
  active-fedora (9.0.0.rc2) lib/active_fedora/relation/finder_methods.rb:79:in `find_take'
  active-fedora (9.0.0.rc2) lib/active_fedora/relation/finder_methods.rb:72:in `take'
  active-fedora (9.0.0.rc2) lib/active_fedora/associations/singular_association.rb:37:in `find_target'
  active-fedora (9.0.0.rc2) lib/active_fedora/associations/association.rb:113:in `load_target'
  active-fedora (9.0.0.rc2) lib/active_fedora/associations/association.rb:34:in `reload'
  active-fedora (9.0.0.rc2) lib/active_fedora/associations/singular_association.rb:11:in `reader'
  active-fedora (9.0.0.rc2) lib/active_fedora/associations/builder/association.rb:63:in `block in define_readers'
  /home/ubuntu/.bundler/ruby/2.2.0/sufia-44d452f4fc1f/sufia-models/app/models/concerns/sufia/generic_file/batches.rb:22:in `processing?'
  /home/ubuntu/.bundler/ruby/2.2.0/sufia-44d452f4fc1f/app/views/my/_index_partials/_list_files.html.erb:8:in `__home_ubuntu__bundler_ruby_______sufia___d___f_fc_f_app_views_my__index_partials__list_files_html_erb___2178894134599913888_70021396149760'
  actionview (4.1.8) lib/action_view/template.rb:145:in `block in render'
```

**Comment by jcoyne** [comment]
Seems like `GenericFile#processing?` is raising an ObjectNotFound error.

**Comment by jcoyne** [comment]
Data was in a bad state. No code problems.

**Comment by mjgiarlo** [comment]
Yes, this is the behavior I saw on UW's instance before adding base_path to fedora.yml.

**Comment by jcoyne** [comment]
The underlying issue is https://github.com/projecthydra/active_fedora/issues/680
